// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jhfmcvzpsholjgluqlbw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpoZm1jdnpwc2hvbGpnbHVxbGJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4MTg5NTMsImV4cCI6MjA2NzM5NDk1M30.q4jw9MjcQ1dPW4cmzDb4FRo7mdA_m6gsnYPxuCZt_rE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});